ElectionProgram/Controllers/CandidatesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElectionProgram.Models;

namespace ElectionProgram.Controllers
{
    public class CandidatesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Candidates
        public ActionResult Index()
        {
            return View(db.Candidate.ToList());
        }

        // GET: Candidates/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidate candidate = db.Candidate.Find(id);
            if (candidate == null)
            {
                return HttpNotFound();
            }
            return View(candidate);
        }

        // GET: Candidates/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Candidates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,NoOfVotes,Name,BirthDate,Gender,NID,Address,Phone,CareerPosition,ImagePath")] Candidate candidate)
        {
            if (ModelState.IsValid)
            {
                db.Candidate.Add(candidate);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(candidate);
        }

        // GET: Candidates/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidate candidate = db.Candidate.Find(id);
            if (candidate == null)
            {
                return HttpNotFound();
            }
            return View(candidate);
        }

        // POST: Candidates/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,NoOfVotes,Name,BirthDate,Gender,NID,Address,Phone,CareerPosition,ImagePath")] Candidate candidate)
        {
            if (ModelState.IsValid)
            {
                db.Entry(candidate).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(candidate);
        }

        // GET: Candidates/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Candidate candidate = db.Candidate.Find(id);
            if (candidate == null)
            {
                return HttpNotFound();
            }
            return View(candidate);
        }

        // POST: Candidates/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Candidate candidate = db.Candidate.Find(id);
            db.Candidate.Remove(candidate);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ElectionProgram/Controllers/HomeController.cs
using ElectionProgram.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectionProgram.Controllers
{
    public class HomeController : Controller
    {
        ApplicationDbContext context = new ApplicationDbContext();
        public ActionResult Index()
        {
             
            return View(context.Candidate.ToList());
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

ElectionProgram/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ElectionProgram/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ElectionProgram/Views/Home/Index.cshtml
@model List< ElectionProgram.Models.Candidate>
@{
    ViewBag.Title = "Election System    ";

}
<link href="~/Content/TemplateStyle.css" rel="stylesheet" />
<link href="~/Content/LoginStyle.css" rel="stylesheet" />
@section header
    {
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            
            <div style="width:570px;float:left"></div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right" style="font-size:22px;float:left;padding-top:25px">
                    <li>@Html.ActionLink("Register", "Registeration", "Account", routeValues: null, htmlAttributes: new { id = "registerLink" })</li>
                    <li>@Html.ActionLink("Log in", "LogIN", "Account", routeValues: null, htmlAttributes: new { id = "loginLink" })</li>
                </ul>

            </div>
            </div>
        </div>

}
<div id="contents">
    <div id="adbox">
        <div class="clearfix">
            <img src="~/Content/images/family-large.jpg" alt="Img" height="382" width="594">
            <div class="detail">
                <h1>It’s never easy...<br> When it comes to family.</h1>
                <p>
                    But we can set<br> everything straight.
                </p>
            </div>
        </div>
    </div>
    <div class="highlight">
        <div class="clearfix">
            <div class="testimonial">
                <h2>Testimonials</h2>
                <p>
                    &ldquo;Aenean ullamcorper purus vitae nisl tristique sollicitudin. Quisque vestibulum, erat ornare.&rdquo;
                </p>
                <span>-John Doe and Jane Doe-</span>
            </div>
            <h1>The Manes Winchester Promise</h1>
            
        </div>
    </div>
    <div class="featured">
        <h1>Our Candidates</h1>
        @foreach (var candidate in Model)
        {
        
            <ul>
                <li class="text-center">
                    <span class="frame1">
                        <span class="box">
                            <img src="@candidate.ImagePath" alt="Img" height="130" width="197">
                        </span>
                    </span>
                    <p>
                        <b>@candidate.Name</b>
                    </p>
                    <span class="btn btn-info" style="text-align:center;color:white">
                        @Html.ActionLink("Read More", "Details", "Candidates", null, new { id = @candidate.ID })
                    </span>
                </li>
            </ul>

        }
    </div>
</div>
<div style="clear:both"></div>
<br />
<br />
<br />
<div id="footer">
    <div class="clearfix">
        <div class="section">
            <h4>Latest News</h4>
            
        </div>
        <div class="section contact">
            <h4>Contact Us</h4>
            <p>
                <span>Address:</span> the address city, state 1111
            </p>
            <p>
                <span>Phone:</span> (+20) 000 222 999
            </p>
            <p>
                <span>Email:</span> info@freewebsitetemplates.com
            </p>
        </div>
        <div class="section">
            <h4>SEND US A MESSAGE</h4>
            <p>
                If you're having problems editing this website template, then don't hesitate to ask for help on the Forums.
            </p>
            <a href="#" class="subscribe">Click to send us an email</a>
        </div>
    </div>
    <div id="footnote">
        <div class="clearfix">
            
            
        </div>
    </div>
    </div>