ElectionProgram/Models/Model/Classes/Voter.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;

namespace ElectionProgram.Models
{
    public class Voter:Employee
    {
        //public int ID { get; set; }
        [DefaultValue(false)]
        public bool IsVote { get; set; }
        public Account Account { get; set;}
        public ICollection<Answer> Answers { get; set; }
    }
}

ElectionProgram/Models/Model/Voter.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ElectionProgram.Models
{
    public class Voter:Employee
    {
        public bool IsVote { get; set; }
        public Account Account { get; set;}
        public ICollection<Answer> Answers { get; set; }
    }
}

ElectionProgram/Controllers/VotersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ElectionProgram.Models;
using ElectionProgram.ViewModel;
using ElectionProgram.ViewModel;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.SignalR;
using ElectionProgram.Hubs;

namespace ElectionProgram.Controllers
{

    public class VotersController : Controller
    {
        string ApplicationUserID;
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Voters
        public ActionResult Index()
        {
            return View(db.Voter.ToList());
        }
        [HttpGet]
        public ActionResult MYPage(string id)
        {
            ApplicationUserID = id;
        ApplicationUser User = (from vo in db.Users
                       where vo.Id == id
                       select vo).FirstOrDefault();
            CandidatesVoter CandidateVoters = new CandidatesVoter()
            {
                AppUser=User,
                VoterID = User.Id,
                canList = db.Candidate.ToList()
            };
            return View(CandidateVoters);
        }
        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [HttpGet]
        public ActionResult ShowCandidate(string id)
        {
            CandidatesVoter ca = new CandidatesVoter { VoterID = id, canList = db.Candidate.ToList() };
            return View(ca);
        }

        public ActionResult Aplay(int id)
        {

            Voter v = (from vo in db.Voter
                       where vo.ID == id
                       select vo).FirstOrDefault();
            db.Voter.Remove(v);
            Candidate c = new Candidate { Name = v.Name, NID = v.NID, BirthDate = v.BirthDate, ImagePath = v.ImagePath };
            db.Candidate.Add(c);
            db.SaveChanges();
            var HubContext = GlobalHost.ConnectionManager.GetHubContext<AdminHub>();
            HubContext.Clients.All.NewCandidate(c);
            return RedirectToAction("Details", "Candidates", new { ID = c.ID });

        }
        public ActionResult IsVoteMessag(string id)
        {

            ApplicationUser AppUser = (from vo in db.Users
                                       where vo.Id == id
                                       select vo).FirstOrDefault();
            return View(AppUser);
        }
       
        [HttpGet]
        public ActionResult Vote(string id)
        {

            ApplicationUser AppUser = (from vo in db.Users
                       where vo.Id == id
                       select vo).FirstOrDefault();
            if (AppUser.IsVote == true)
            {
                return RedirectToAction("IsVoteMessag", new { ID = id });
            }
            else
            {
                CandidatesVoter ca = new CandidatesVoter { VoterID = id, canList = db.Candidate.ToList() };
                return View(ca);
            }

        }
        [HttpPost]
        public ActionResult Vote(int CandidateId,string VoterID)
        {
            
            ApplicationUser AppUser = (from APPUSER in db.Users
                       where APPUSER.Id == VoterID
                       select APPUSER).FirstOrDefault();
            if (AppUser.IsVote == true)
            {
                return RedirectToAction("MYPage", new { id = VoterID });
            }
            else
            {
                var candidate = (from c in db.Candidate
                          where c.ID == CandidateId
                          select c).FirstOrDefault();
                candidate.NoOfVotes += 1;
                AppUser.IsVote = true;
                CandidateVoter cv = new CandidateVoter { candidate_id = candidate.ID, ApplicationUserID = AppUser.Id };
                db.CandidateVoter.Add(cv);
                db.SaveChanges();

                return RedirectToAction("MYPage", new { id = VoterID });
            }
        }


        // GET: Voters/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Voter voter = db.Voter.Find(id);
            if (voter == null)
            {
                return HttpNotFound();
            }
            return View(voter);
        }

        // GET: Voters/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Voters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Create([Bind(Include = "ID,Name,BirthDate,Gender,NID,Address,Phone,CareerPosition,ImagePath")] Voter voter, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                if (file != null)
                {
                    string path = HttpContext.Server.MapPath("~/Content/images/");
                    file.SaveAs(path + file.FileName);

                    voter.ImagePath = "/Content/images/" + file.FileName;
                }

                db.Voter.Add(voter);
                db.SaveChanges();
                return RedirectToAction("MYPage", new { id = voter.ID });
            }
            else
            {
                return View(voter);
            }
        }
       
        // GET: Voters/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Voter voter = db.Voter.Find(id);
            if (voter == null)
            {
                return HttpNotFound();
            }
            return View(voter);
        }

        // POST: Voters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,BirthDate,Gender,NID,Address,Phone,CareerPosition,ImagePath")] Voter voter, HttpPostedFileBase file)
        {
            if (ModelState.IsValid)
            {
                
                db.Entry(voter).State = EntityState.Modified;
                if (file != null)
                {
                    string path = HttpContext.Server.MapPath("~/Content/images/");
                    file.SaveAs(path + file.FileName);

                    voter.ImagePath = "/Content/images/" + file.FileName;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(voter);
        }
        // GET: Voters/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Voter voter = db.Voter.Find(id);
            if (voter == null)
            {
                return HttpNotFound();
            }
            return View(voter);
        }

        // POST: Voters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        { 

            Voter voter = db.Voter.Find(id);
            db.Voter.Remove(voter);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult ShowResult(string ID)
        {
            
            Election ele = (from e in db.Election
                            select e).FirstOrDefault();
            var AppuserID = User.Identity.GetUserId();
            CandidatesVoter electionCandidate = new CandidatesVoter()
            {
                ElectionId = ele.ID,
                canList = db.Candidate.ToList(),
                VoterID = ID
            };

            if (ele.EndDate < System.DateTime.Now)
            {
                return View(electionCandidate);
            }
            else
            {
                return RedirectToAction("ShowWinner");
            }
        }
        //[HttpPost]
        //public ActionResult ShowResult(ElectionCadidates electionCandidate)
        //{

        //    Election e = (from ele in db.Election
        //                  where ele.ID == electionCandidate.ElectionId
        //                  select ele).FirstOrDefault();

        //    if (e.EndDate<System.DateTime.Now)
        //    {
        //        return View(electionCandidate);
        //    }
        //    else
        //    {
        //        return RedirectToAction("ShowWinner");
        //    }
        //}

        public ActionResult ShowWinner()
        {
            var Top2Candidate = (from c in db.Candidate
                                 select c).OrderByDescending(c => c.NoOfVotes).Take(2).ToList();

            if (Top2Candidate[0].NoOfVotes == Top2Candidate[1].NoOfVotes)
            {
                return RedirectToAction("RepeatedElection");

            }
            //else if (Top2Candidate[0].NoOfVotes > Top2Candidate[1].NoOfVotes)
           
            //    return View(Top2Candidate[0]);
            
            return View(Top2Candidate[0]);
        }
        public ActionResult RepeatedElection()
        {
            var Top2Candidate = (from c in db.Candidate
                                 select c).OrderByDescending(c => c.NoOfVotes).Take(2).ToList();
            return View(Top2Candidate);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }

ElectionProgram/Views/Voters/Create.cshtml
@model ElectionProgram.Models.Voter

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}


<h2>Create</h2>


@section header{
    
    <div>Register Voter </div>
}

@using (Html.BeginForm("Create", "Voters", FormMethod.Post, new { enctype = "multipart/form-data" }))
{ 

    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Voter</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { @type = "date", htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CareerPosition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CareerPosition, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CareerPosition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                        <input id="ImagePath" class="btn btn-default" title="Upload a image"type="file" name="file" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>
@section scripts{
        @Scripts.Render("~/bundles/jqueryval")
    }

ElectionProgram/Views/Voters/Delete.cshtml
@model ElectionProgram.Models.Voter

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}


@section header
    {
    <div> </div>
}
<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Voter</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CareerPosition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CareerPosition)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ImagePath)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ElectionProgram/Views/Voters/Details.cshtml
@model ElectionProgram.Models.Voter

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}

@section header
    {
    <div> </div>
}
<h2>Details</h2>

<div>
    <h4>Voter</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BirthDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BirthDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Gender)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Phone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CareerPosition)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CareerPosition)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>

        <dd>
            <img src="@Model.ImagePath" width="150" height="150" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ElectionProgram/Views/Voters/Edit.cshtml
@model ElectionProgram.Models.Voter

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}

@section header
    {
    <div> </div>
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Voter</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.BirthDate, new { @type = "date", @class = "form-control", @Value = Model.BirthDate.ToString("yyyy-MM-dd") })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Gender, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CareerPosition, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CareerPosition, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CareerPosition, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ImagePath, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img src="@Model.ImagePath" width="150" height="150" />
                <input id="ImagePath" class="btn btn-default" title="Upload a image" type="file" name="file" />

            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

ElectionProgram/Views/Voters/Index.cshtml
@model IEnumerable<ElectionProgram.Models.Voter>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}

@section header{
    <div>voter page</div>
}
<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Gender)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Phone)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CareerPosition)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ImagePath)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BirthDate)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Gender)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NID)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Phone)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CareerPosition)
        </td>
        <td>
            <img src="@item.ImagePath" width="150" height="150"/>
        </td>
        <td>
            @Html.ActionLink("Home", "Home", new { id=item.ID }) |
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>

ElectionProgram/Views/Voters/MYPage.cshtml
@model ElectionProgram.ViewModel.CandidatesVoter

@{
    ViewBag.Title = "@Model.UserName";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}
<link href="~/Content/TemplateStyle.css" rel="stylesheet" />

@section header{
    <div>
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle"  data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
        
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"style="font-size:20px;margin-top:20px">
                    <li>@Html.ActionLink("show candidates","ShowCandidate", new { id= Model.VoterID })</li>
                    <li>@Html.ActionLink("Vote", "Vote",new {  id = Model.VoterID })</li>
                    <li>@Html.ActionLink("Aplay As Candidate", "Aplay", new { id = Model.VoterID })</li>
                    <li>@Html.ActionLink("Show Election Result", "ShowResult", "Voters", new { id = Model.VoterID })</li>
                </ul>
               
                <span ><img src="@Model.AppUser.ImagePath " width=50 height=50 /></span>
                <span class="icon-bar" style="color:white;font-size:20px;margin:50px"> @Model.AppUser.UserName </span>
                          
            </div>
        </div>
    </div>
}

<div class="featured">
    <h2>Our Candidates</h2>
    @foreach (var candidate in Model.canList)
    {

        <ul>
            <li class="text-center">
                <span class="frame1">
                    <span class="box">
                        <img src="@candidate.ImagePath" alt="Img" height="130" width="197">
                    </span>
                </span>
                <p>
                    <b>@candidate.Name</b>
                </p>
                <span class="btn btn-info" style="text-align:center;color:white">
                    @Html.ActionLink("Read More", "Details", "Candidates", null, new { id = @candidate.ID })
                </span>
            </li>
        </ul>

    }
</div>
</div>
<div style="clear:both"></div>

<div id="footer">
    <div class="clearfix">
        <div class="section">
            <h4>Latest News</h4>

        </div>
        <div class="section contact">
            <h4>Contact Us</h4>
            <p>
                <span>Address:</span> the address city, state 1111
            </p>
            <p>
                <span>Phone:</span> (+20) 000 222 999
            </p>
            <p>
                <span>Email:</span> info@freewebsitetemplates.com
            </p>
        </div>
        <div class="section">
            <h4>SEND US A MESSAGE</h4>
            <p>
                If you're having problems editing this website template, then don't hesitate to ask for help on the Forums.
            </p>
            <a href="http://www.freewebsitetemplates.com/misc/contact/" class="subscribe">Click to send us an email</a>
        </div>
    </div>
    <div id="footnote">
        <div class="clearfix">
            <div class="connect">
                <a href="http://freewebsitetemplates.com/go/facebook/" class="facebook"></a><a href="http://freewebsitetemplates.com/go/twitter/" class="twitter"></a><a href="http://freewebsitetemplates.com/go/googleplus/" class="googleplus"></a><a href="http://pinterest.com/fwtemplates/" class="pinterest"></a>
            </div>

        </div>
    </div>
</div>

ElectionProgram/Views/Voters/Vote.cshtml
@model  ElectionProgram.ViewModel.CandidatesVoter
@{
    ViewBag.Title = "Vote";
    Layout = "~/Views/Shared/_MyLayout.cshtml";
}
@section header{
    <div>Votting Page</div>
}
<div style="margin-top:20px"></div>
    
        @using (Html.BeginForm("Vote", "Voters", FormMethod.Post))
        {
            
            foreach (var item in Model.canList)
            {
              <div style="background-color:#f2f2f2 ;margin-top:10px" >@item.Name </div>
                // @Html.RadioButton("id", @item.ID,new {@unchecked=true} ) <span>Vote</span>
               <input name="CandidateId"type="radio" value="@item.ID"/>
                  
                @Html.Hidden("VoterID", Model.VoterID)
                
                   }
              <br />
              <input type="submit" value="Applay Vote"class="btn btn-primary" />
               }


              @Html.ActionLink("Goto MYPage", "MYPage", new { id = Model.VoterID })